Develop
sovchenko/rozetka_automation_project pull request #5
Opened 2020-01-08 21:56 UTC by sovchenko

new pull request

2020-01-09 08:58 UTC, toleksyn requested changes

2020-01-09 08:58 UTC, toleksyn commented on Jenkinsfile
> +    //if
remove

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_elements/filter_section/Filter.java
> +public class Filter {
be specific, ProductFilter

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_elements/filter_section/Filter.java
> +                .filter(option -> option.find(By.xpath(".//label")).getText().contains(filterOptionTitle))
chain with new line if more than 2 methods

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_elements/filter_section/Filter.java
> +
remove

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_elements/filter_section/FiltersBlock.java
> +public class FiltersBlock {
try to have more detailed decomposition

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_elements/filter_section/FiltersBlock.java
> +                .filter(s -> s.getFilterTitle().contains(filterTitle))
rename s

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_elements/items_grid/ItemTile.java
> +
fix

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_elements/items_grid/ItemTile.java
> +public class ItemTile {
be specific - ProductTile

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_elements/items_grid/ItemTile.java
> +
add behaviour

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_elements/items_grid/ItemsGrid.java
> +    public ItemsGrid(ElementsCollection collection) {
move to method getTiles(limitNumber)

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_elements/items_grid/ItemsGrid.java
> +public class ItemsGrid {
ProductsGrid

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_elements/items_grid/ItemsGrid.java
> +                    tile.setItemPrice(itemTileElement.find(By.xpath(".//span[@class='goods-tile__price-value']")).getText());
avoid inline method calls, extract to variables

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_objects/BasePage.java
>      @Step("Log in as user")
extract to header

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_objects/BasePage.java
>      public String getNameOfLoggedInUser() {
getLoggedInUserName()

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_objects/CheckoutDialogPage.java
> +}
// extension purpose only
add comment

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_objects/HomePage.java
> +        Selenide.sleep(2000);
avoid, element collection doesn't wait, use .shouldBe()

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_objects/ItemPage.java
> +    private SelenideElement reviewLinks = $x("//a[@class='product__rating-reviews']");
singular

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_objects/ItemPage.java
> +        //used regex which replaces all non-digit characters with empty string
no need to comment self explanatory code

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_objects/ItemPage.java
> +        return this;
create an object

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_objects/ItemPage.java
> +    public String getHeaderOfReviewsSection() {
getReviewTitle()

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_objects/ListItemsPage.java
> +
remove

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_objects/ListItemsPage.java
> +        Selenide.sleep(3000);
remove

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_objects/ListItemsPage.java
> +
remove,
move behaviour to tile object

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_objects/ReviewsPage.java
> +}
!!

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_objects/SearchResultsPage.java
> +
!!

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_objects/SearchResultsPage.java
> +}
re-do into objects

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_objects/WishListPage.java
> +}
!!

2020-01-09 08:58 UTC, toleksyn commented on src/test/java/tests/FilterTest.java
> +package tests;
com.softserveinc.atqc for all packages

2020-01-09 08:58 UTC, toleksyn commented on src/test/java/tests/FilterTest.java
> +
!!

2020-01-09 08:58 UTC, toleksyn commented on src/main/java/page_objects/HomePage.java
> +    public static HomePage openHomePage() {
no static methods in PO

2020-01-09 08:58 UTC, toleksyn commented on src/test/java/tests/FilterTest.java
> +        val listItemsPage = HomePage.openHomePage()
fix by inlining selenide elements to getter or methods

2020-01-09 08:58 UTC, toleksyn commented on src/test/java/tests/FilterTest.java
> +        val listItemsPage = HomePage.openHomePage()
new HomePage().open()

2020-01-09 08:58 UTC, toleksyn commented on src/test/java/tests/FilterTest.java
> +    }
val

2020-01-09 08:58 UTC, toleksyn commented on src/test/java/tests/FilterTest.java
> +        //Assert.assertEquals(actualRate,expectedRate);
add comment

2020-01-09 08:58 UTC, toleksyn commented on src/test/java/tests/FilterTest.java
> +}
!!

2020-01-09 08:58 UTC, toleksyn commented on src/test/java/tests/FilterTest.java
> +        Assert.assertEquals(actualTitle, expectedTitle);
stat imp

2020-01-09 08:58 UTC, toleksyn commented on src/test/java/tests/LoginTest.java
> +
!!!

2020-01-12 11:15 UTC, sovchenko commented on Jenkinsfile
> +    //if
done

2020-01-12 11:15 UTC, sovchenko commented on src/main/java/page_elements/filter_section/Filter.java
> +public class Filter {
done

2020-01-12 11:20 UTC, sovchenko commented on src/main/java/page_elements/filter_section/FiltersBlock.java
> +public class FiltersBlock {
done

2020-01-12 11:20 UTC, sovchenko commented on src/main/java/page_elements/filter_section/Filter.java
> +
done

2020-01-12 11:20 UTC, sovchenko commented on src/main/java/page_elements/filter_section/Filter.java
> +                .filter(option -> option.find(By.xpath(".//label")).getText().contains(filterOptionTitle))
done

2020-01-12 11:20 UTC, sovchenko commented on src/test/java/tests/FilterTest.java
> +    }
done

2020-01-12 11:21 UTC, sovchenko commented on src/test/java/tests/FilterTest.java
> +        //Assert.assertEquals(actualRate,expectedRate);
assertion was removed

2020-01-12 11:21 UTC, sovchenko commented on src/test/java/tests/FilterTest.java
> +}
done

2020-01-12 11:22 UTC, sovchenko commented on src/test/java/tests/FilterTest.java
> +        Assert.assertEquals(actualTitle, expectedTitle);
done

2020-01-12 11:22 UTC, sovchenko commented on src/test/java/tests/LoginTest.java
> +
done

2020-01-12 11:23 UTC, closed without merging

2020-01-12 11:23 UTC, sovchenko commented
concerns from all comments were resolved