Develop
sovchenko/rozetka_automation_project pull request #7
Opened 2020-01-20 14:51 UTC by sovchenko

2020-01-21 07:28 UTC, toleksyn requested changes

2020-01-21 07:28 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_elements/items_grid/ProductTile.java
>      public ProductReviewsTab openProductReviews() {
openProductReviewsTab()
fix step

2020-01-21 07:28 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_elements/items_grid/ProductTile.java
> +        int reviewsAmount = Integer.parseInt(
val
stat imp

2020-01-21 07:28 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_elements/menu/MenuCategories.java
> +public enum MenuCategories {
singular

2020-01-21 07:28 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_elements/menu/MenuCategories.java
> +    PhonesTVsElectronics("telefony-tv-i-ehlektronika"), ComputersLaptops("computers-notebooks");
code convention

2020-01-21 07:28 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_elements/menu/MenuCategories.java
> +    MenuCategories(String categoryName) {
@RequiredArgsConstructor

2020-01-21 07:28 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_elements/menu/SubmenuCategories.java
> +}
same as above

2020-01-21 07:28 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_elements/product_filters/ManufacturerProductFilter.java
> +        val checkboxXpath = String.format("//a[@class='checkbox-filter__link' and contains(@href,'producer=%s')]",
stat imp

2020-01-21 07:28 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_elements/product_filters/ManufacturerProductFilter.java
> +    @Step("Hide manufacturer filter")
fix steps, must be consistent

2020-01-21 07:28 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_elements/product_filters/product_filter_values/Manufacturers.java
> +}
same

2020-01-21 07:28 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_elements/product_filters/product_filter_values/Manufacturers.java
> +}
use Enum.name()

2020-01-21 07:28 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_objects/HomePage.java
> +        Selenide.open("https://rozetka.com.ua/");
create a property file, move URL there

2020-01-21 07:28 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_objects/HomePage.java
> +        String menuCategoryXpath = String.format("//a[@class='menu-categories__link' and contains(@href,'%s')]", category);
val, stat imp

2020-01-21 07:28 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_objects/HomePage.java
> +        $x(subCategoryXpath).click();
same

2020-01-21 07:28 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_objects/ProductPage.java
> +    private int removeAllNonDigitsCharactersOfTheElementText(SelenideElement element) {
parseToText()

2020-01-21 07:28 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_objects/ProductsListPage.java
> +
split into vars

2020-01-21 07:33 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_elements/product_filters/PriceRangeProductFilter.java
> +        $x("//ctg-filter-slider[@class='filter_layout_sidebar']/../../../../../button").click();
avoid absolute locators

2020-01-21 07:35 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_elements/product_page_elements/ProductBuyTogetherTab.java
>  public class ProductBuyTogetherTab {
this is not a page element

2020-01-21 07:37 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_objects/UserAccountPage.java
>      private Header header = new Header();
you already have this from base page

2020-01-21 07:37 UTC, toleksyn commented on src/test/java/com/softserveinc/atqc/tests/LoginTest.java
>                  .logIn("ezbooksforme@gmail.com", "Pa55word");
move to properties

2020-01-21 07:38 UTC, toleksyn commented on src/test/java/com/softserveinc/atqc/tests/LoginTest.java
>          val nameOfLoggedInUser = homePage.getHeader().getLoggedInUserName();
revert Of

2020-01-21 08:12 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_objects/ProductsListPage.java
> +                    val productTile = new ProductTile();
pass tileElement here

2020-01-21 08:12 UTC, toleksyn commented on src/main/java/com/softserveinc/atqc/page_objects/ProductsListPage.java
> +                    if (tileElement.find(By.xpath(ratingXpath)).exists()) {
stat imp
xpath() from Selenide

2020-01-21 08:14 UTC, toleksyn commented on src/test/java/com/softserveinc/atqc/tests/ProductFilterTest.java
> +                .hoverMenuCategory(PhonesTVsElectronics.getCategoryName())
hoverMenuCategory(PhonesTVsElectronics)

2020-01-24 19:35 UTC, sovchenko commented on src/main/java/com/softserveinc/atqc/page_elements/items_grid/ProductTile.java
>      public ProductReviewsTab openProductReviews() {
done

2020-01-24 19:35 UTC, sovchenko commented on src/main/java/com/softserveinc/atqc/page_elements/items_grid/ProductTile.java
> +        int reviewsAmount = Integer.parseInt(
done

2020-01-24 19:35 UTC, sovchenko commented on src/main/java/com/softserveinc/atqc/page_elements/menu/MenuCategories.java
> +public enum MenuCategories {
done

2020-01-24 19:35 UTC, sovchenko commented on src/main/java/com/softserveinc/atqc/page_elements/menu/MenuCategories.java
> +    PhonesTVsElectronics("telefony-tv-i-ehlektronika"), ComputersLaptops("computers-notebooks");
done

2020-01-24 19:38 UTC, sovchenko commented on src/main/java/com/softserveinc/atqc/page_objects/HomePage.java
> +        String menuCategoryXpath = String.format("//a[@class='menu-categories__link' and contains(@href,'%s')]", category);
done

2020-01-24 19:38 UTC, sovchenko commented on src/main/java/com/softserveinc/atqc/page_objects/HomePage.java
> +        $x(subCategoryXpath).click();
done

2020-01-24 19:50 UTC, sovchenko commented on src/main/java/com/softserveinc/atqc/page_objects/ProductsListPage.java
> +
done

2020-01-24 20:09 UTC, sovchenko commented on src/main/java/com/softserveinc/atqc/page_elements/product_filters/PriceRangeProductFilter.java
> +        $x("//ctg-filter-slider[@class='filter_layout_sidebar']/../../../../../button").click();
done

2020-01-24 20:20 UTC, sovchenko commented on src/main/java/com/softserveinc/atqc/page_objects/UserAccountPage.java
>      private Header header = new Header();
done

2020-01-24 20:28 UTC, sovchenko commented on src/main/java/com/softserveinc/atqc/page_elements/product_page_elements/ProductBuyTogetherTab.java
>  public class ProductBuyTogetherTab {
done

2020-01-25 08:57 UTC, sovchenko commented on src/main/java/com/softserveinc/atqc/page_elements/menu/MenuCategories.java
> +    MenuCategories(String categoryName) {
done

2020-01-25 08:58 UTC, sovchenko commented on src/main/java/com/softserveinc/atqc/page_objects/ProductPage.java
> +    private int removeAllNonDigitsCharactersOfTheElementText(SelenideElement element) {
done

2020-01-25 09:28 UTC, sovchenko commented on src/main/java/com/softserveinc/atqc/page_objects/ProductsListPage.java
> +                    if (tileElement.find(By.xpath(ratingXpath)).exists()) {
done

2020-01-25 09:42 UTC, sovchenko commented on src/test/java/com/softserveinc/atqc/tests/ProductFilterTest.java
> +                .hoverMenuCategory(PhonesTVsElectronics.getCategoryName())
done

2020-01-26 14:30 UTC, closed without merging